<?php

/**
 * @file
 * Contains hook and preprocess functions for drucal.module.
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row() for the event migration.
 */
function drucal_migrate_event_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  // @todo Do things here maybe?
}
